#!/usr/bin/env python3
"""Generate the library catalog so Conductor can always see what's available.

Single source of truth: the YAML frontmatter of every content `.md` file
(`software_dev` tier, plus `stack`/`version` for stack books). This script scans
the numbered topic folders and emits three artifacts, all deterministic (no
timestamps, stable sort) so re-runs produce clean git diffs:

  - LIBRARY_INDEX.json  — machine-readable manifest the Conductor app consumes
                          (per-category files + a stacks/versions map for
                          `stack@major` edition selection). Carries the library
                          `version` read from the root `VERSION` file.
  - README.md           — the human navigable index (English), regenerated
                          between the AUTO-INDEX markers (intro above is manual).
  - README.pt-BR.md     — the same navigable index in Portuguese.

The library **version** lives in the root `VERSION` file (single source of
truth). Bump the patch digit on every change; on `99` rollover, bump the minor.
This script stamps that version into LIBRARY_INDEX.json and both READMEs, so the
displayed version can never drift from the file.

Usage:
    python scripts/build_index.py            # write artifacts
    python scripts/build_index.py --check     # verify they are up to date (CI)

Run from anywhere; paths are resolved relative to the repo root.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VERSION_PATH = REPO_ROOT / "VERSION"

# Display titles for each numbered topic folder, keyed by the NN prefix.
CATEGORY_TITLES = {
    "00": "Academic Curriculum (reading lists)",
    "01": "Programming Languages",
    "02": "Algorithms & Data Structures",
    "03": "Software Design & Architecture",
    "04": "Software Engineering & Practices",
    "05": "Databases & Data",
    "06": "Web & Frontend",
    "07": "DevOps, SRE & Operations",
    "08": "Distributed Systems & Microservices",
    "09": "Security & Privacy",
    "10": "AI & LLM",
    "11": "Management, Product & Process",
    "12": "Design & UX",
    "13": "Automation & Integration",
    "14": "Frameworks",
}

# Portuguese display titles for the pt-BR README.
CATEGORY_TITLES_PT = {
    "00": "Currículo Acadêmico (listas de leitura)",
    "01": "Linguagens de Programação",
    "02": "Algoritmos & Estruturas de Dados",
    "03": "Design & Arquitetura de Software",
    "04": "Engenharia & Práticas de Software",
    "05": "Bancos de Dados & Dados",
    "06": "Web & Frontend",
    "07": "DevOps, SRE & Operações",
    "08": "Sistemas Distribuídos & Microsserviços",
    "09": "Segurança & Privacidade",
    "10": "IA & LLM",
    "11": "Gestão, Produto & Processo",
    "12": "Design & UX",
    "13": "Automação & Integração",
    "14": "Frameworks",
}

# Per-language prose used inside the generated AUTO-INDEX region.
GENERATED_NOTE = {
    "en": ("> **Generated by `scripts/build_index.py` — do not edit by hand.** "
           "It mirrors [LIBRARY_INDEX.json](LIBRARY_INDEX.json), the machine-readable "
           "catalog Conductor consumes."),
    "pt": ("> **Gerado por `scripts/build_index.py` — não edite à mão.** "
           "Espelha o [LIBRARY_INDEX.json](LIBRARY_INDEX.json), o catálogo legível por "
           "máquina que o Conductor consome."),
}
VERSION_LINE = {
    "en": ("> **Library version:** `{v}` — from [`VERSION`](VERSION). "
           "Bump the patch digit on every change (`99` → next minor)."),
    "pt": ("> **Versão da biblioteca:** `{v}` — de [`VERSION`](VERSION). "
           "Incremente o dígito _patch_ a cada mudança (`99` → próximo _minor_)."),
}
TOTAL_LINE = {
    "en": "**Total: {n} book/reading-list files**",
    "pt": "**Total: {n} arquivos de livro/lista de leitura**",
}
TITLES = {"en": CATEGORY_TITLES, "pt": CATEGORY_TITLES_PT}

FOLDER_RE = re.compile(r"^(\d{2})_")
START_MARKER = "<!-- AUTO-INDEX:START -->"
END_MARKER = "<!-- AUTO-INDEX:END -->"

# README file -> language of its generated region.
README_TARGETS = [("README.md", "en"), ("README.pt-BR.md", "pt")]


def read_version() -> str:
    """The library version — single source of truth is the root VERSION file."""
    try:
        return VERSION_PATH.read_text(encoding="utf-8").strip()
    except OSError:
        return "0.0.0"


def parse_frontmatter(text: str) -> dict[str, str]:
    """Return the leading YAML frontmatter as a flat dict of scalar values."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end]
    data: dict[str, str] = {}
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, value = line.partition(":")
        data[key.strip()] = value.strip()
    return data


def url_path(rel_path: str) -> str:
    """Encode a repo-relative path the way the README links do: space and # only."""
    return rel_path.replace("%", "%25").replace(" ", "%20").replace("#", "%23")


def collect() -> list[dict]:
    """Walk the numbered topic folders and return one record per content file."""
    categories: list[dict] = []
    for folder in sorted(p for p in REPO_ROOT.iterdir() if p.is_dir() and FOLDER_RE.match(p.name)):
        nn = folder.name[:2]
        files = []
        for md in sorted(folder.glob("*.md"), key=lambda p: p.name):
            fm = parse_frontmatter(md.read_text(encoding="utf-8"))
            rel = f"{folder.name}/{md.name}"
            record = {
                "path": rel,
                "title": md.stem,
                "tier": fm.get("software_dev"),
            }
            if fm.get("stack"):
                record["stack"] = fm["stack"]
            if fm.get("version"):
                try:
                    record["version"] = int(fm["version"])
                except ValueError:
                    record["version"] = fm["version"]
            files.append(record)
        if files:
            categories.append(
                {
                    "id": folder.name,
                    "number": nn,
                    "title": CATEGORY_TITLES.get(nn, folder.name),
                    "files": files,
                }
            )
    return categories


def build_stacks(categories: list[dict]) -> dict:
    """Group stack books by id, exposing the versions available for selection."""
    stacks: dict[str, dict] = {}
    for cat in categories:
        for f in cat["files"]:
            sid = f.get("stack")
            if not sid:
                continue
            entry = stacks.setdefault(sid, {"versions": [], "editions": []})
            edition = {"path": f["path"], "title": f["title"]}
            if "version" in f:
                edition["version"] = f["version"]
                if f["version"] not in entry["versions"]:
                    entry["versions"].append(f["version"])
            entry["editions"].append(edition)
    for entry in stacks.values():
        entry["versions"].sort(key=lambda v: (isinstance(v, str), v))
        entry["editions"].sort(key=lambda e: (e.get("version", 0), e["title"]))
    return dict(sorted(stacks.items()))


def build_manifest(categories: list[dict], stacks: dict, version: str) -> dict:
    total = sum(len(c["files"]) for c in categories)
    return {
        "schema": "conductor-library-index/v1",
        "version": version,
        "totals": {
            "files": total,
            "categories": len(categories),
            "stacks": len(stacks),
        },
        "categories": categories,
        "stacks": stacks,
    }


def render_readme_index(categories: list[dict], version: str, lang: str) -> str:
    """Render the markdown catalog placed between the AUTO-INDEX markers."""
    titles = TITLES[lang]
    lines: list[str] = []
    lines.append(GENERATED_NOTE[lang])
    lines.append("")
    lines.append(VERSION_LINE[lang].format(v=version))
    lines.append("")
    for cat in categories:
        lines.append(f"## {cat['number']} · {titles.get(cat['number'], cat['title'])}")
        lines.append("")
        for f in cat["files"]:
            lines.append(f"- [{f['title']}]({url_path(f['path'])})")
        lines.append("")
    total = sum(len(c["files"]) for c in categories)
    lines.append("---")
    lines.append("")
    lines.append(TOTAL_LINE[lang].format(n=total))
    return "\n".join(lines)


def update_readme(readme_text: str, index_md: str) -> str:
    block = f"{START_MARKER}\n\n{index_md}\n\n{END_MARKER}"
    if START_MARKER in readme_text and END_MARKER in readme_text:
        pre = readme_text[: readme_text.index(START_MARKER)]
        post = readme_text[readme_text.index(END_MARKER) + len(END_MARKER):]
        return f"{pre}{block}{post}"
    # Bootstrap: replace from the first generated heading onward, keep the intro.
    anchor = readme_text.find("## 00 ")
    pre = readme_text[:anchor] if anchor != -1 else readme_text.rstrip() + "\n\n"
    return f"{pre}{block}\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if artifacts are stale (for CI)")
    args = ap.parse_args()

    version = read_version()
    categories = collect()
    stacks = build_stacks(categories)
    manifest = build_manifest(categories, stacks, version)

    json_path = REPO_ROOT / "LIBRARY_INDEX.json"
    new_json = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"

    readmes = []  # (path, new_text)
    for fname, lang in README_TARGETS:
        path = REPO_ROOT / fname
        if not path.is_file():
            continue
        new_text = update_readme(path.read_text(encoding="utf-8"),
                                 render_readme_index(categories, version, lang))
        readmes.append((path, new_text))

    if args.check:
        stale = []
        if json_path.read_text(encoding="utf-8") != new_json:
            stale.append("LIBRARY_INDEX.json")
        for path, new_text in readmes:
            if path.read_text(encoding="utf-8") != new_text:
                stale.append(path.name)
        if stale:
            print("STALE: " + ", ".join(stale) + " — run: python scripts/build_index.py")
            return 1
        print("Index up to date.")
        return 0

    json_path.write_text(new_json, encoding="utf-8")
    for path, new_text in readmes:
        path.write_text(new_text, encoding="utf-8")
    print(f"Wrote LIBRARY_INDEX.json and {len(readmes)} README file(s) "
          f"(v{version}; {manifest['totals']['files']} files, "
          f"{manifest['totals']['categories']} categories, "
          f"{manifest['totals']['stacks']} stacks).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
